"""remove queues

Revision ID: d454d456d596
Revises: b115d8e37aa2
Create Date: 2024-05-07 20:19:31.027845

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd454d456d596'
down_revision = 'b115d8e37aa2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('queue')
    op.drop_table('linkqueue')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('linkqueue',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('linkrequest_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('position', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['linkrequest_id'], ['linkrequests.id'], name='linkqueue_linkrequest_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='linkqueue_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='linkqueue_pkey')
    )
    op.create_table('queue',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('request_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('position', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], name='queue_request_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='queue_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='queue_pkey')
    )
    # ### end Alembic commands ###
